from ammy_inventory import lambda_handler

test = {
    'resource': '/products',
    'path': '/products/0b2ce0c4-9d06-11ed-ad90-11575fda8a45/records',
    'httpMethod': 'POST',
    'headers': None,
    'multiValueHeaders': None,
    'queryStringParameters': None,
    'multiValueQueryStringParameters': None,
    'pathParameters': None,
    'stageVariables': None,
    'requestContext': {'resourceId': '1gzx1d',
                       'resourcePath': '/products',
                       'httpMethod': 'GET',
                       'extendedRequestId': 'e7GdwExdvHcFq2A=',
                       'requestTime': '18/Jan/2023:05:32:07 +0000',
                       'path': '/products/1234567',
                       'accountId': '387458999228',
                       'protocol': 'HTTP/1.1',
                       'stage': 'test-invoke-stage',
                       'domainPrefix': 'testPrefix',
                       'requestTimeEpoch': 1674019927868,
                       'requestId': 'f0b3697c-33c3-4765-a9b7-4caffc71e467',
                       'identity': {'cognitoIdentityPoolId': None,
                                    'cognitoIdentityId': None,
                                    'apiKey': 'test-invoke-api-key',
                                    'principalOrgId': None,
                                    'cognitoAuthenticationType': None,
                                    'userArn': 'arn:aws:iam::387458999228:root',
                                    'apiKeyId': 'test-invoke-api-key-id',
                                    'userAgent': 'aws-internal/3 aws-sdk-java/1.12.358 Linux/5.4.225-139.416.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.352-b10 java/1.8.0_352 vendor/Oracle_Corporation cfg/retry-mode/standard',
                                    'accountId': '387458999228',
                                    'caller': '387458999228',
                                    'sourceIp': 'test-invoke-source-ip',
                                    'accessKey': 'ASIAVUNS3EO6B67R2HNW',
                                    'cognitoAuthenticationProvider': None,
                                    'user': '387458999228'},
                       'domainName': 'testPrefix.testDomainName',
                       'apiId': 'bz7bxn9zqk'},
    'body': '{"type":1,"date":1674115200000,"count":-30,"price":0}',
    'isBase64Encoded': False}

lambda_handler(test, None)
